# Generated by Django 4.2.14 on 2024-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_boardinghouse_bh_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='admin_faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
