# Generated by Django 4.2.14 on 2024-08-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_adminfaceimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='vault_password',
        ),
        migrations.AlterField(
            model_name='owner',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='fingerprint',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
