import { Link } from "react-router-dom";

const Home = () => {
    return (
        <div style={{ 
            height: "100vh", 
            padding: "20px", 
            backgroundColor: "#232323", 
            color: "white", 
            display: "flex", 
            flexDirection: "column", 
            justifyContent: "center", 
            alignItems: "center", 
            textAlign: "center" 
        }}>
            <h1 style={{ 
                fontSize: "48px", 
                marginBottom: "20px",
                lineHeight: "1.2"
            }}>
                Homepage
            </h1>
            <p style={{ 
                fontSize: "18px", 
                marginBottom: "30px", 
                maxWidth: "600px", 
                lineHeight: "1.5",
            }}>
                This project was generated by{" "}
                <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
                    Dhiwise
                </a>
                . Quickly use the links below to navigate through all pages.
            </p>

            <div style={{ 
                display: "grid", 
                gridTemplateColumns: "repeat(2, minmax(0, 1fr))", 
                gap: "20px", 
                width: "100%", 
                maxWidth: "600px" 
            }}>
                <ul style={{ listStyle: "none", padding: "0", margin: "0" }}>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/splashscreen" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            Splashscreen
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/bhregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BHRegistration
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/ownerregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            OwnerRegistration
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/bhinfo" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BHInfo
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/boarderregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BoarderRegistration
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/guardianregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            GuardianRegistration
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/billregistration" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BillRegistration
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/boarderregistrationsuccessful" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BoarderRegistrationSuccessful
                        </Link>
                    </li>
                </ul>

                <ul style={{ listStyle: "none", padding: "0", margin: "0" }}>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/transactions" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            Transactions
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/boarderprofile" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BoarderProfile
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/paynow" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            PayNow
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/billdetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BillDetails
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/dashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            AdminDashboard
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/reportsummary" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            ReportSummary
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/roominfo" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            RoomInfo
                        </Link>
                    </li>
                    <li style={{ marginBottom: "10px" }}>
                        <Link to="/boardersinfo" style={{ color: "#87CEFA", textDecoration: "none" }}>
                            BoarderInfo
                        </Link>
                    </li>
                </ul>
            </div>
        </div>
    );
};

export default Home;
